# global configs
Global:
  mode: inference    # evaluation, inference
  category: detection3d
  output_dir: ./output/
  save_inference_dir: ./inference

# model architecture

Model:
  name: CENTERPOINT
  backend: powervr_grpc   #clas_sim, paddle, powervr
  head_ops:
    - ReOutputsKey:
        dim: tvm_infer_0_out_0.bin
        height: tvm_infer_0_out_1.bin
        hm: tvm_infer_0_out_2.bin
        reg: tvm_infer_0_out_3.bin
        rot: tvm_infer_0_out_4.bin
    - Reshape:
        dim: [1, 3, 248, 216]
        height: [1, 1, 248, 216]
        hm: [1, 1, 248, 216]
        reg: [1, 2, 248, 216]
        rot: [1, 2, 248, 216]

  PowerVR_gRPC:
    pvr_server: 10.80.51.217
    input_name: velodyne
    output_shape: [1000]

Infer:
  infer_datas:
    velodyne:
      - C:/Users/Zhuoran.Lv/OneDrive - Imagination Technologies/Desktop/mini kitti/kitti mini data object veloyne/testing/velodyne/000001.bin
  batch_size: 1
  transform_ops:
    - LoadVelodyne:
        num_point_dim: 4 
    - HardVoxelize:
        point_cloud_range: [0,-39,-3,69,39,1]
        voxel_size: [.16,.16,4]
        max_points_in_voxel: 100
        max_voxel_num: 2000
    - BatchData: {}
    - ReOutputsKey:
        coors: coords
        num_points_in_voxel: num_points_per_voxel
  postprocess_ops:
    - CenterPointDecoder:
        test_cfg:
          post_center_limit_range: [-10., -50., -10., 80., 50., 10.]
          nms:
            nms_pre_max_size: 1000
            nms_post_max_size: 83
            nms_iou_threshold: 0.1
          score_threshold: 0.1
          point_cloud_range: [0, -39.68, -3, 69.12, 39.68, 1]
          down_ratio: 2
          voxel_size: [0.16, 0.16, 4]
    - RotateNMS:
        iou_threshold: 0.3
        max_keep: 5